version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: carebox
      MONGO_INITDB_ROOT_PASSWORD: _carebox2022.
      MONGO_INITDB_DATABASE: carebox
      wiredTigerCacheSizeGB: 4
    ports:
      - 27017:27017
    volumes:
      - ./init-db.d:/docker-entrypoint-initdb.d
      
